export type Team = 'boy' | 'girl'

export interface Player {
  name: string
  aliases: string[]
  team: Team
}

export const players: Player[] = [
  // 🧑 Boy team
  { name: 'Irfansyah Riyanto', aliases: ['Irfansyah', 'Irfan'], team: 'boy' },
  { name: 'Nur Roni Dinnurohman', aliases: ['Roni'], team: 'boy' },
  { name: 'Dicky Fria Senjaya', aliases: ['Dicky'], team: 'boy' },
  { name: 'Ervan Abu Nangim', aliases: ['Ervan'], team: 'boy' },
  { name: 'Miftah Rahmat', aliases: ['Miftah'], team: 'boy' },
  { name: 'Eko Waluyo', aliases: ['Eko'], team: 'boy' },
  { name: 'Ismail Fathan Nur Aziz', aliases: ['Ismail', 'Fathan'], team: 'boy' },
  { name: 'Muhammad Akbar Abdul Jabbar', aliases: ['Akbar'], team: 'boy' },
  { name: 'M Fajar Aditia', aliases: ['Fajar'], team: 'boy' },
  { name: 'Weilly Nur Rahman', aliases: ['Weilly'], team: 'boy' },
  { name: 'Riki Haryadi', aliases: ['Riki'], team: 'boy' },
  { name: 'Faisal Hanafi', aliases: ['Faisal'], team: 'boy' },
  { name: 'Harry Pujianto', aliases: ['Harry'], team: 'boy' },
  { name: 'Vicry Syavat Muhammad', aliases: ['Vicry'], team: 'boy' },
  { name: 'Permadi', aliases: ['Permadi'], team: 'boy' },
  { name: 'Raihan Naji Al Ghifary', aliases: ['Raihan'], team: 'boy' },
  { name: 'Rian Ariona', aliases: ['Rian'], team: 'boy' },
  { name: 'Adhi Prasetya', aliases: ['Adhi'], team: 'boy' },
  { name: 'Fajar Saputra', aliases: ['Fajar Saputra'], team: 'boy' },
  { name: 'Haris Fakhrizal', aliases: ['Haris'], team: 'boy' },
  { name: 'Ferdy', aliases: ['Ferdy'], team: 'boy' },
  { name: 'Ruslan Hidayat', aliases: ['Ruslan', 'Lan'], team: 'boy' },

  // 👧 Girl team
  { name: 'Dea Sunarwan', aliases: ['Dea'], team: 'girl' },
  { name: 'Anita Rizki Wulandari', aliases: ['Anita'], team: 'girl' },
  { name: 'Jeni Juliana', aliases: ['Jeni'], team: 'girl' },
  { name: 'Mesha Febrianty Yolanda', aliases: ['Mesha'], team: 'girl' },
  { name: 'Nur Tiara Artini', aliases: ['Tiara'], team: 'girl' },
  { name: 'Sari Roswati', aliases: ['Sari'], team: 'girl' },
  { name: 'Shela Aulia', aliases: ['Shela'], team: 'girl' },
  { name: 'Trisna Komalasari', aliases: ['Trisna'], team: 'girl' },
  { name: 'Nur Rani Dinnurohman', aliases: ['Rani'], team: 'girl' },
  { name: 'Astri Febrianti', aliases: ['Astri'], team: 'girl' },
  { name: 'Asny Sukri Rahayu', aliases: ['Asny'], team: 'girl' },
  { name: 'Atin Siti Nopia', aliases: ['Atin'], team: 'girl' },
  { name: 'Eli Iltikhoiyah', aliases: ['Eli'], team: 'girl' },
  { name: 'Hanna Nadianingrum', aliases: ['Hanna'], team: 'girl' },
  { name: 'Kayla Salsabil', aliases: ['Kayla'], team: 'girl' },
  { name: 'Maryam Arisa Anggraeni', aliases: ['Maryam'], team: 'girl' },
  { name: 'Neng Sabillah', aliases: ['Sabillah'], team: 'girl' },
  { name: 'Putri Rahayu Nurbaiti', aliases: ['Putri'], team: 'girl' },
  { name: 'Yustin Afriliana', aliases: ['Yustin'], team: 'girl' },
  { name: 'Aminah Tri Rahayu', aliases: ['Aminah'], team: 'girl' },
  { name: 'Arin Nurul Annisa', aliases: ['Arin'], team: 'girl' },
  { name: 'Dheajeng Fitri Yani', aliases: ['Dhea'], team: 'girl' },
  { name: 'Rahma Fitriyani', aliases: ['Rahma'], team: 'girl' },
  { name: 'Tasya Putri Agustina', aliases: ['Tasya'], team: 'girl' },
  { name: 'Alya Istiana Annisa', aliases: ['Alya'], team: 'girl' },
  { name: 'Aufatin Nisa Salsabila', aliases: ['Aufatin', 'Nisa'], team: 'girl' },
  { name: 'Dini Jamilah', aliases: ['Dini'], team: 'girl' },
  { name: 'Ismi Nurul Fatimah', aliases: ['Ismi'], team: 'girl' },
  { name: 'Imania Azkiya Mukhlisa', aliases: ['Imania'], team: 'girl' },
  { name: 'Musyaffa Rachma Adhe Putera', aliases: ['Musyaffa'], team: 'girl' },
  { name: 'Neneng Saraswati', aliases: ['Neneng'], team: 'girl' },
  { name: 'Sri Aprilianti Rahayu', aliases: ['Sri'], team: 'girl' },
  { name: 'Nida Hanifah Muthiah', aliases: ['Nida'], team: 'girl' },
  { name: 'Nisa Rahmawati', aliases: ['Nisa'], team: 'girl' },
  { name: 'Bias Ahsha Swasi', aliases: ['Bias'], team: 'girl' },
  { name: 'Romi Pratiwi', aliases: ['Romi'], team: 'girl' },
  { name: 'Yuni Yuningsih', aliases: ['Yuni'], team: 'girl' },
  { name: 'Yeni', aliases: ['Yeni'], team: 'girl' },
]
