export type Team = 'boy' | 'girl'

export interface Player {
  name: string
  aliases: string[]
  team: Team
}

export const players: Player[] = [
  // 🧑 Boy team
  { name: 'Irfansyah Riyanto', aliases: ['Irfansyah', 'Irfan', 'Bang Irfansyah', 'Bang Irfan'], team: 'boy' },
  { name: 'Dea Sunarwan', aliases: ['Dea', 'Kang Dea'], team: 'boy' },
  { name: 'Nur Roni Dinnurohman', aliases: ['Onnay','Onay','Kang Onnay','Kang Onay'], team: 'boy' },
  { name: 'Dicky Fria Senjaya', aliases: ['Dicky','Kang Dicky'], team: 'boy' },
  { name: 'Ervan Abu Nangim', aliases: ['Ervan','Om Abu','Om Ervan'], team: 'boy' },
  { name: 'Miftah Rahmat', aliases: ['Miftah','Kang Miftah'], team: 'boy' },
  { name: 'Eko Waluyo', aliases: ['Eko','Kang Eko','Mang Eko'], team: 'boy' },
  { name: 'Ismail Fathan Nur Aziz', aliases: ['Ismail', 'Fathan', 'Kang Ismail', 'Kang Fathan','Mail','Kang Mail'], team: 'boy' },
  { name: 'Muhammad Akbar Abdul Jabbar', aliases: ['Bisma','Kang Bisma'], team: 'boy' },
  { name: 'M Fajar Aditia', aliases: ['Fajar','Kang Fajar'], team: 'boy' },
  { name: 'Weilly Nur Rahman', aliases: ['Weilly','Kang Weilly','Welly','Kang Welly'], team: 'boy' },
  { name: 'Riki Haryadi', aliases: ['Riki','Kang Riki'], team: 'boy' },
  { name: 'Faisal Hanafi', aliases: ['Faisal','Kang Faisal'], team: 'boy' },
  { name: 'Harry Pujianto', aliases: ['Harry','Kang Harry'], team: 'boy' },
  { name: 'Vicry Syavat Muhammad', aliases: ['Vicry','Kang Vicry'], team: 'boy' },
  { name: 'Permadi', aliases: ['Permadi','Kang Permadi','Kang Adi Pepeng','Pepeng','Adi Pepeng'], team: 'boy' },
  { name: 'Raihan Naji Al Ghifary', aliases: ['Raihan','Kang Raihan'], team: 'boy' },
  { name: 'Rian Ariona', aliases: ['Rian','Kang Rian'], team: 'boy' },
  { name: 'Adhi Prasetya', aliases: ['Adhi','Kang Adhi'], team: 'boy' },
  { name: 'Fajar Saputra', aliases: ['Fajar Sapu','Kang Fajar Sapu'], team: 'boy' },
  { name: 'Haris Fakhrizal', aliases: ['Ustadz Haris','Kang Haris','Haris'], team: 'boy' },
  { name: 'Ferdy', aliases: ['Ferdy','Kang Ferdy'], team: 'boy' },
  { name: 'Ruslan Hidayat', aliases: ['Ruslan', 'Lan','Kang Ruslan','Kang Lan'], team: 'boy' },
  { name: 'Jeni Juliana', aliases: ['Jeni','Mang Jeni','Kang Jeni'], team: 'boy' },
  { name: 'Asny Sukri Rahayu', aliases: ['Asny','Kang Asny'], team: 'boy' },

  // 👧 Girl team
  { name: 'Anita Rizki Wulandari', aliases: ['Anita','Teh Anita'], team: 'girl' },
  { name: 'Mesha Febrianty Yolanda', aliases: ['Mesha','Teh Mesha','Meisya','Teh Meisya'], team: 'girl' },
  { name: 'Nur Tiara Artini', aliases: ['Tiara','Teh Tiara'], team: 'girl' },
  { name: 'Sari Roswati', aliases: ['Sari','Teh Sari'], team: 'girl' },
  { name: 'Shela Aulia', aliases: ['Shela','Teh Shela'], team: 'girl' },
  { name: 'Trisna Komalasari', aliases: ['Trisna','Teh Trisna'], team: 'girl' },
  { name: 'Nur Rani Dinnurohman', aliases: ['Rani','Teh Rani'], team: 'girl' },
  { name: 'Astri Febrianti', aliases: ['Astri','Teh Astri'], team: 'girl' },
  { name: 'Atin Siti Nopia', aliases: ['Atin','Teh Atin'], team: 'girl' },
  { name: 'Eli Iltikhoiyah', aliases: ['Eli','Teh Eli'], team: 'girl' },
  { name: 'Hanna Nadianingrum', aliases: ['Hanna','Teh Hanna'], team: 'girl' },
  { name: 'Kayla Salsabil', aliases: ['Kayla','Teh Kayla'], team: 'girl' },
  { name: 'Maryam Arisa Anggraeni', aliases: ['Maryam','Teh Maryam'], team: 'girl' },
  { name: 'Neng Sabillah', aliases: ['Sabillah','Teh Sabillah'], team: 'girl' },
  { name: 'Putri Rahayu Nurbaiti', aliases: ['Putri','Teh Putri'], team: 'girl' },
  { name: 'Yustin Afriliana', aliases: ['Yustin','Teh Yustin'], team: 'girl' },
  { name: 'Aminah Tri Rahayu', aliases: ['Aminah','Teh Aminah'], team: 'girl' },
  { name: 'Arin Nurul Annisa', aliases: ['Arin','Teh Arin'], team: 'girl' },
  { name: 'Dheajeng Fitri Yani', aliases: ['Dhea','Teh Dhea'], team: 'girl' },
  { name: 'Rahma Fitriyani', aliases: ['Rahma','Teh Rahma'], team: 'girl' },
  { name: 'Tasya Putri Agustina', aliases: ['Tasya','Teh Tasya'], team: 'girl' },
  { name: 'Alya Istiana Annisa', aliases: ['Alya','Teh Alya'], team: 'girl' },
  { name: 'Dini Jamilah', aliases: ['Dini','Teh Dini'], team: 'girl' },
  { name: 'Ismi Nurul Fatimah', aliases: ['Ismi','Teh Ismi'], team: 'girl' },
  { name: 'Imania Azkiya Mukhlisa', aliases: ['Imania','Teh Imania'], team: 'girl' },
  { name: 'Musyaffa Rachma Adhe Putera', aliases: ['Musyaffa','Teh Musyaffa'], team: 'girl' },
  { name: 'Neneng Saraswati', aliases: ['Neneng','Teh Neneng'], team: 'girl' },
  { name: 'Sri Aprilianti Rahayu', aliases: ['Sri','Teh Sri'], team: 'girl' },
  { name: 'Nida Hanifah Muthiah', aliases: ['Nida','Teh Nida'], team: 'girl' },
  { name: 'Nisa Rahmawati', aliases: ['Nisa','Teh Nisa'], team: 'girl' },
  { name: 'Aufatin Nisa Salsabila', aliases: ['Aufatin','Teh Aufatin'], team: 'girl' },
  { name: 'Bias Ahsha Swasi', aliases: ['Bias','Teh Bias'], team: 'girl' },
  { name: 'Romi Pratiwi', aliases: ['Romi','Teh Romi'], team: 'girl' },
  { name: 'Yuni Yuningsih', aliases: ['Yuni','Teh Yuni'], team: 'girl' },
  { name: 'Yeni', aliases: ['Yeni','Teh Yeni'], team: 'girl' },
]
